### PR TITLE
new content

### LINKED ISSUE #1: in progress
Refer to outline in [Readme](https://github.com/learn-co-curriculum/sqlite-data-types) for content to be included.

deadline: 9/15/15

### PR DESCRIPTION
**Pull request by SophieDeBenedetto**
needs :eyes: 

closes #1 

@AnnJohn @dfenjves @ipc103 @deniznida @aviflombaum

### CODE REVIEW

**Comment by AnnJohn** [comment]
@dfenjves Could you review this one?

**Comment by dfenjves** [comment]
Sure, assign away.

**Comment by AnnJohn** [comment]
:+1: @dfenjves 

Deadline: 9/11/2015

**Comment by dfenjves** [comment]
Good to merge.

**Pull request merged**
